name: Google Docs to CSV Export
on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:     # Allow manual triggering

permissions:
  contents: write  # Allow pushing to repository

jobs:
  export-google-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pandas
          
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - name: Create service account key file
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > service_account_key.json
          
      - name: Run Google Docs export script
        run: python3 tests/export_google_docs.py
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          
      - name: Upload to Google Cloud Storage
        run: |
          echo "Uploading to gs://${{ secrets.GCS_BUCKET_NAME }}/"
          gsutil cp fathom_docs_content.csv gs://${{ secrets.GCS_BUCKET_NAME }}/
          gsutil cp fathom_docs_metadata.csv gs://${{ secrets.GCS_BUCKET_NAME }}/
          
          echo "Verifying upload..."
          gsutil ls -l gs://${{ secrets.GCS_BUCKET_NAME }}/fathom_docs_content.csv
          gsutil ls -l gs://${{ secrets.GCS_BUCKET_NAME }}/fathom_docs_metadata.csv
          
      - name: Save metadata to repository
        run: |
          git config --local user.email "gaby@motherduck.com"
          git config --local user.name "pulidogaby"
          
          # Only commit the metadata file (not the full content)
          git add fathom_docs_metadata.csv
          git diff --staged --quiet || git commit -m "Update Google Docs metadata - $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: google-docs-export
          path: |
            fathom_docs_content.csv
            fathom_docs_metadata.csv
            
      - name: Clean up sensitive files
        run: rm -f service_account_key.json
        if: always()